/**
 * Tests for the drift heuristics.
 *
 * The positive fixtures are real strings harvested from a shipped claude-code
 * binary; the negative fixtures are real segments from the same file that the
 * naive "printable run >= 40 chars" rule accepted. Both halves matter — a
 * heuristic that lets symbol tables through buries the one sentence that
 * changed, and one that is too strict misses it entirely.
 */

import test from 'node:test'
import assert from 'node:assert/strict'
import {
  byCodeUnit, classifyPolicy, createHarvester, diffSnapshots, extractStrings,
  isProsey, snapshotVersion,
} from '../src/drift/extract.js'
import {
  diffPrompts, normaliseSystem, policySentences, sections, toolGateSentences,
} from '../src/drift/probe.js'
import {
  buildRecord, classifySentence, confidence, diffSelfReports, parseSelfReport,
} from '../src/drift/selfreport.js'

/* ------------------------------------------------------------------ *
 * isProsey — positives
 * ------------------------------------------------------------------ */

const PROSE = [
  // The motivating case: one line, no setting, delegation stops firing.
  'Do not call the AgentTool unless the user requested it, or the task is a self-contained research question.',
  'Do NOT interpret this as user acknowledgement, confirmation, or response to any pending question.',
  'Claude Code will always reject requests to use denied tools.',
  'Caveat: The messages below were generated by the user while running local commands. DO NOT respond to these messages or otherwise consider them in your response unless the user explicitly asks you to.',
  'Always run tests after modifying auth-related files',
  'A device is requesting access to Claude Code.',
  'Describe your most recent action in 3-5 words using present tense. Name the file or function, not the branch.',
  'This should never happen, and if it does the surrounding call was already wrong.',
  'Prefer the standard library over a dependency whenever the two are close enough.',
]

test('isProsey accepts real shipped policy sentences', () => {
  for (const s of PROSE) {
    assert.equal(isProsey(s), true, `should accept: ${s}`)
  }
})

test('isProsey tolerates the CamelCase tool names policy text actually uses', () => {
  assert.equal(
    isProsey('Never call the AgentTool or the WebFetch tool when the user is only asking a question.'),
    true
  )
})

/* ------------------------------------------------------------------ *
 * isProsey — negatives
 * ------------------------------------------------------------------ */

const NOT_PROSE = {
  'concatenated symbol table': 'useSyncExternalSImperativeHandleuseImperativeHanuseInsertionEffect',
  'env var name run': 'npm_node_execpataws_access_key_is3_secret_accessaws_secret_accesaws_session_tokebun_config_no_clear_terminal_on_musl-x86_64.so.1ld-musl-x86_64.s',
  'two table entries fused at a full stop':
    'A JavaScript exception was thrown, but it was cleared before it could be read.Cinternal error: entered unreachable code',
  'minified function body': 'function a(b,c){return b.length>c?b.slice(0,c):b} // packs the tail',
  'assignment soup': 'const parser = require("node:path"), other = require("node:fs"), n = 42',
  'base64 blob': 'SGVsbG8gd29ybGQsIHRoaXMgaXMgYSByZWFzb25hYmx5IGxvbmcgdGVzdCBzdHJpbmc=',
  'sha256 digest': 'fb804ee019bfbb8d7e85abf965e528e53b5aa5a4e4ebc0f164139dc10a9e0320',
  'url with trailing words': 'https://api.example.com/v1/messages is the endpoint that we should be calling now',
  'path list': 'src/graph/partition.js src/graph/report.js src/graph/scan.js src/drift/extract.js src/drift/cmd.js',
  'constant name in caps': 'ACCESS CONTROL ALLOW ORIGIN HEADER VALUE WAS NOT SET',
  'camelCase identifier run': 'getUserById setUserName deleteUserRecord updateUserEmail findUserByEmail listUserRoles hasUserRole',
  'version table': 'Version 1.2.3 build 4567 rev 89012 hash 34567 date 20260817 tag 991',
  'operator soup': 'value && other || fallback ? left : right ; next => done , last',
  'too short to be policy': 'Do not call the AgentTool.',
  'no verb anywhere': 'Red green blue yellow orange purple magenta cyan turquoise indigo violet',
  'template literal fragment': 'the file ${path} could not be read because ${reason} happened here',
  'starts mid-token': 'ition-image-pairview-transition-transition-group and then some more words here',
  'mostly punctuation': 'a. b, c; d: e! f? g. h, i; j: k! l? m. n, o; p: q! r? s. t, u; v: w! x?',
}

test('isProsey rejects minified and table-shaped strings from a real bundle', () => {
  for (const [label, s] of Object.entries(NOT_PROSE)) {
    assert.equal(isProsey(s), false, `should reject (${label}): ${s.slice(0, 60)}`)
  }
})

test('isProsey handles non-strings and empties without throwing', () => {
  assert.equal(isProsey(undefined), false)
  assert.equal(isProsey(null), false)
  assert.equal(isProsey(12345), false)
  assert.equal(isProsey(''), false)
  assert.equal(isProsey('   '), false)
})

test('isProsey length bounds are configurable and enforced at both ends', () => {
  const short = 'Do not call it when the user says no'
  assert.equal(isProsey(short), false)
  assert.equal(isProsey(short, { minLength: 20 }), true)
  const long = 'Do not call the AgentTool unless the user asked for it. '.repeat(20)
  assert.equal(isProsey(long), false)
  assert.equal(isProsey(long, { maxLength: 2000 }), true)
})

test('isProsey rejects strings carrying control characters', () => {
  assert.equal(isProsey('Do not call the AgentTool unless' + String.fromCharCode(0) + ' the user requested it here'), false)
  assert.equal(isProsey('Do not call the AgentTool unless' + String.fromCharCode(0xe9) + ' the user requested it here'), false)
})

/* ------------------------------------------------------------------ *
 * extractStrings
 * ------------------------------------------------------------------ */

const FAKE_BUNDLE =
  'var t=0;const A="Do not call the AgentTool unless the user requested it, or you were told to.";' +
  'const B={mode:"fast",n:42};function q(a,b){return a<b?a:b}' +
  'const C="Always confirm with the user before you delete a file that you did not create.";' +
  'const D="Do not call the AgentTool unless the user requested it, or you were told to.";' +
  'const E="useSyncExternalStoreuseImperativeHandleuseInsertionEffect";'

test('extractStrings pulls prose out of a bundle and drops the code around it', () => {
  const out = extractStrings(FAKE_BUNDLE)
  assert.deepEqual(out, [
    'Always confirm with the user before you delete a file that you did not create.',
    'Do not call the AgentTool unless the user requested it, or you were told to.',
  ])
})

test('extractStrings is deduped, sorted by code unit, and reproducible', () => {
  const a = extractStrings(FAKE_BUNDLE)
  const b = extractStrings(FAKE_BUNDLE)
  assert.deepEqual(a, b)
  assert.deepEqual([...a].sort(byCodeUnit), a)
  assert.equal(new Set(a).size, a.length)
})

test('extractStrings accepts a Buffer as well as a string', () => {
  assert.deepEqual(extractStrings(Buffer.from(FAKE_BUNDLE, 'latin1')), extractStrings(FAKE_BUNDLE))
})

test('extractStrings splits on the escaped newlines a multi-line prompt is stored with', () => {
  const packed =
    '"You are a helpful assistant that answers the question asked.' +
    '\\nDo not call the AgentTool unless the user requested it here.' +
    '\\nAlways report what you changed before you finish the turn."'
  const out = extractStrings(packed)
  assert.equal(out.length, 3)
  assert.ok(out.includes('Do not call the AgentTool unless the user requested it here.'))
  assert.ok(out.includes('Always report what you changed before you finish the turn.'))
})

test('extractStrings ignores binary noise between literals', () => {
  const noisy = Buffer.concat([
    Buffer.from([0, 1, 2, 255, 254, 7]),
    Buffer.from('Do not call the AgentTool unless the user requested it here.', 'latin1'),
    Buffer.from([0, 0, 3, 200]),
  ])
  assert.deepEqual(extractStrings(noisy), [
    'Do not call the AgentTool unless the user requested it here.',
  ])
})

/* ------------------------------------------------------------------ *
 * createHarvester — the streaming path used on a 240 MB binary
 * ------------------------------------------------------------------ */

test('createHarvester recovers a sentence split across a chunk boundary', () => {
  const sentence = 'Do not call the AgentTool unless the user requested it, or you were told to.'
  const h = createHarvester()
  h.push('"' + sentence.slice(0, 30))
  h.push(sentence.slice(30) + '";var x=1')
  const { strings, truncated } = h.finish()
  assert.deepEqual(strings, [sentence])
  assert.equal(truncated, false)
})

test('createHarvester recovers an escape sequence split across a chunk boundary', () => {
  const h = createHarvester()
  h.push('"Always tell the user what you changed before you stop.\\')
  h.push('nDo not call the AgentTool unless the user requested it here."')
  const { strings } = h.finish()
  assert.deepEqual(strings, [
    'Always tell the user what you changed before you stop.',
    'Do not call the AgentTool unless the user requested it here.',
  ])
})

test('createHarvester flushes a trailing segment that never met a delimiter', () => {
  const h = createHarvester()
  h.push('"Always tell the user what you changed before you stop this turn.')
  assert.deepEqual(h.finish().strings, [
    'Always tell the user what you changed before you stop this turn.',
  ])
})

test('createHarvester reports truncation when it hits the limit', () => {
  const h = createHarvester({ limit: 2 })
  for (let i = 0; i < 6; i++) {
    h.push(`"Always tell the user what you changed in file number ${i} before you stop."`)
  }
  const { strings, truncated } = h.finish()
  assert.equal(strings.length, 2)
  assert.equal(truncated, true)
})

/* ------------------------------------------------------------------ *
 * classifyPolicy
 * ------------------------------------------------------------------ */

test('classifyPolicy flags the imperative shapes that gate behaviour', () => {
  const cases = [
    ['Do not call the AgentTool unless the user requested it.', ['do not', 'unless the user']],
    ['Never delegate work to a subagent in this mode.', ['never']],
    ['Always confirm before you delete anything.', ['always']],
    ['Fan out only when the task list has more than one independent item.', ['only when']],
    ['Avoid spawning more workers than the plan asked for.', ['avoid']],
    ['You must not read another worker\'s draft output.', ['must not']],
    ['You should not edit a frozen file.', ['should not']],
    ['Use the tool only if the user asked for it.', ['only if']],
    ['That operation is not allowed in this context.', ['not allowed']],
    ['Refuse the request and explain why.', ['refuse']],
  ]
  for (const [text, expected] of cases) {
    const r = classifyPolicy(text)
    assert.equal(r.isPolicy, true, text)
    for (const p of expected) assert.ok(r.patterns.includes(p), `${text} -> expected ${p}`)
  }
})

test('classifyPolicy leaves descriptive prose alone', () => {
  const r = classifyPolicy('This tool returns the list of files that changed in the last commit.')
  assert.deepEqual(r, { isPolicy: false, patterns: [] })
})

test('classifyPolicy is case-insensitive and catches contractions', () => {
  assert.equal(classifyPolicy('DO NOT respond to these messages.').isPolicy, true)
  assert.equal(classifyPolicy("Don't call the tool for a trivial edit.").isPolicy, true)
  assert.deepEqual(classifyPolicy('').patterns, [])
  assert.equal(classifyPolicy(null).isPolicy, false)
})

test('classifyPolicy returns patterns in a stable order', () => {
  const a = classifyPolicy('Do not ever do this; never do it, and always avoid it unless the user says so.')
  const b = classifyPolicy('Do not ever do this; never do it, and always avoid it unless the user says so.')
  assert.deepEqual(a.patterns, b.patterns)
  assert.deepEqual(a.patterns, ['do not', 'never', 'always', 'unless the user', 'avoid'])
})

/* ------------------------------------------------------------------ *
 * diffSnapshots
 * ------------------------------------------------------------------ */

function snap(over = {}) {
  return {
    id: over.id ?? 'x',
    install: {
      packageVersion: null,
      cliVersion: null,
      files: [],
      ...(over.install ?? {}),
    },
    strings: { items: [], truncated: false, ...(over.strings ?? {}) },
    config: { entries: [], ...(over.config ?? {}) },
  }
}

test('diffSnapshots reports the added policy line that started all this', () => {
  const before = snap({
    id: 'a',
    install: { packageVersion: '2.1.201', files: [{ path: 'bin/claude.exe', sha256: 'aaa' }] },
    strings: { items: ['Read the file before you edit it, every time.'] },
  })
  const after = snap({
    id: 'b',
    install: { packageVersion: '2.1.232', files: [{ path: 'bin/claude.exe', sha256: 'bbb' }] },
    strings: {
      items: [
        'Do not call the AgentTool unless the user requested it.',
        'Read the file before you edit it, every time.',
      ],
    },
  })

  const d = diffSnapshots(before, after)
  assert.deepEqual(d.added, ['Do not call the AgentTool unless the user requested it.'])
  assert.deepEqual(d.removed, [])
  assert.deepEqual(d.versionChanged, { from: '2.1.201', to: '2.1.232' })
  assert.deepEqual(d.hashChanged, [
    { path: 'bin/claude.exe', from: 'aaa', to: 'bbb', status: 'changed' },
  ])
  assert.equal(d.policyAdded.length, 1)
  assert.deepEqual(d.policyAdded[0].patterns, ['do not', 'unless the user'])
  assert.deepEqual(d.policyRemoved, [])
  assert.equal(d.from, 'a')
  assert.equal(d.to, 'b')
})

test('diffSnapshots reports nothing when the two sides are identical', () => {
  const s = snap({
    install: { packageVersion: '2.1.232', files: [{ path: 'a.js', sha256: 'aaa' }] },
    strings: { items: ['Always confirm before you delete a file you did not create.'] },
    config: { entries: [{ path: 'settings.json', sha256: 'ccc' }] },
  })
  const d = diffSnapshots(s, JSON.parse(JSON.stringify(s)))
  assert.deepEqual(d.added, [])
  assert.deepEqual(d.removed, [])
  assert.equal(d.versionChanged, null)
  assert.equal(d.cliVersionChanged, null)
  assert.deepEqual(d.hashChanged, [])
  assert.deepEqual(d.configChanged, [])
  assert.deepEqual(d.policyAdded, [])
})

test('diffSnapshots separates a removed constraint from an added one', () => {
  const before = snap({ strings: { items: ['Never delegate without asking the user first.'] } })
  const after = snap({ strings: { items: ['Always delegate when the task list is independent.'] } })
  const d = diffSnapshots(before, after)
  assert.equal(d.policyAdded.length, 1)
  assert.deepEqual(d.policyAdded[0].patterns, ['always'])
  assert.equal(d.policyRemoved.length, 1)
  assert.deepEqual(d.policyRemoved[0].patterns, ['never'])
})

test('diffSnapshots tracks files that appeared or vanished, not just changed', () => {
  const before = snap({ install: { files: [{ path: 'old.js', sha256: 'aaa' }] } })
  const after = snap({ install: { files: [{ path: 'new.js', sha256: 'bbb' }] } })
  const d = diffSnapshots(before, after)
  assert.deepEqual(d.hashChanged, [
    { path: 'new.js', from: null, to: 'bbb', status: 'added' },
    { path: 'old.js', from: 'aaa', to: null, status: 'removed' },
  ])
})

test('diffSnapshots counts a local config change as drift', () => {
  const before = snap({ config: { entries: [{ path: 'hooks/a.js', sha256: 'aaa' }] } })
  const after = snap({
    config: {
      entries: [
        { path: 'hooks/a.js', sha256: 'zzz' },
        { path: 'hooks/b.js', sha256: 'bbb' },
      ],
    },
  })
  const d = diffSnapshots(before, after)
  assert.deepEqual(d.configChanged, [
    { path: 'hooks/a.js', from: 'aaa', to: 'zzz', status: 'changed' },
    { path: 'hooks/b.js', from: null, to: 'bbb', status: 'added' },
  ])
})

test('diffSnapshots falls back to the cli version when no package version exists', () => {
  const before = snap({ install: { cliVersion: '2.1.201' } })
  const after = snap({ install: { cliVersion: '2.1.232' } })
  const d = diffSnapshots(before, after)
  assert.deepEqual(d.versionChanged, { from: '2.1.201', to: '2.1.232' })
  assert.deepEqual(d.cliVersionChanged, { from: '2.1.201', to: '2.1.232' })
})

test('diffSnapshots propagates truncation so a capped diff is not read as real', () => {
  const before = snap({ strings: { items: ['a'], truncated: true } })
  const after = snap({ strings: { items: ['b'] } })
  assert.equal(diffSnapshots(before, after).truncated, true)
  assert.equal(diffSnapshots(snap(), snap()).truncated, false)
})

test('diffSnapshots survives malformed or empty snapshots', () => {
  const d = diffSnapshots({}, {})
  assert.deepEqual(d.added, [])
  assert.equal(d.versionChanged, null)
  assert.deepEqual(d.hashChanged, [])
  assert.equal(diffSnapshots(undefined, undefined).policyAdded.length, 0)
})

test('diffSnapshots output ordering is stable regardless of input ordering', () => {
  const items = ['Zebra crossings are never painted here at all.', 'Always look before you cross the road.']
  const a = snap({ strings: { items: [] } })
  const b = snap({ strings: { items } })
  const c = snap({ strings: { items: [...items].reverse() } })
  assert.deepEqual(diffSnapshots(a, b).added, diffSnapshots(a, c).added)
  assert.deepEqual(diffSnapshots(a, b).added, [...items].sort(byCodeUnit))
})

/* ------------------------------------------------------------------ *
 * misc helpers
 * ------------------------------------------------------------------ */

test('snapshotVersion prefers the package version and degrades to null', () => {
  assert.equal(snapshotVersion(snap({ install: { packageVersion: '1.0.0', cliVersion: '2.0.0' } })), '1.0.0')
  assert.equal(snapshotVersion(snap({ install: { cliVersion: '2.0.0' } })), '2.0.0')
  assert.equal(snapshotVersion(snap()), null)
  assert.equal(snapshotVersion(undefined), null)
})

test('byCodeUnit is a total order that does not depend on locale', () => {
  const input = ['b', 'A', 'a', 'B', 'Z', 'z']
  assert.deepEqual([...input].sort(byCodeUnit), ['A', 'B', 'Z', 'a', 'b', 'z'])
  assert.equal(byCodeUnit('a', 'a'), 0)
})

/* ------------------------------------------------------------------ *
 * probe.js — parsing the prompt as the service delivers it
 *
 * Pure functions only. startProxy opens a socket and is exercised out of band.
 * ------------------------------------------------------------------ */

test('normaliseSystem handles both shapes the Messages API accepts', () => {
  assert.deepEqual(normaliseSystem('a plain string prompt'), {
    blocks: [{ index: 0, text: 'a plain string prompt', cached: false, chars: 21 }],
    text: 'a plain string prompt',
  })

  const arr = normaliseSystem([
    { type: 'text', text: 'first', cache_control: { type: 'ephemeral' } },
    { type: 'text', text: 'second' },
  ])
  assert.equal(arr.text, 'first\n\nsecond')
  assert.deepEqual(arr.blocks.map((b) => b.cached), [true, false])
  assert.deepEqual(arr.blocks.map((b) => b.index), [0, 1])
})

test('normaliseSystem degrades instead of throwing on junk', () => {
  assert.deepEqual(normaliseSystem(null), { blocks: [], text: '' })
  assert.deepEqual(normaliseSystem(undefined), { blocks: [], text: '' })
  assert.deepEqual(normaliseSystem(42), { blocks: [], text: '' })
  // A block with no text field yields an empty block, not the string "undefined".
  assert.deepEqual(normaliseSystem([{ notText: 1 }]).blocks[0], {
    index: 0, text: '', cached: false, chars: 0,
  })
})

const PROMPT_A = `You are Claude Code.

# Tool use

You may call tools to accomplish the task.

# Delegation

Use the AgentTool to fan out when the task list has independent items.`

const PROMPT_B = `You are Claude Code.

# Tool use

You may call tools to accomplish the task.

# Delegation

Do not call the AgentTool unless the user requested it.

# Safety

Never read another worker's draft output.`

test('sections splits a delivered prompt on its headings', () => {
  const s = sections(PROMPT_A)
  assert.deepEqual(s.map((x) => x.heading), ['(preamble)', 'Tool use', 'Delegation'])
  assert.equal(s[0].body, 'You are Claude Code.')
  assert.ok(s[2].body.includes('AgentTool'))
  assert.equal(s[0].hash.length, 12)
})

test('sections hashes are stable and change only with content', () => {
  const a = sections(PROMPT_A)
  const b = sections(PROMPT_A)
  assert.deepEqual(a.map((x) => x.hash), b.map((x) => x.hash))
  const changed = sections(PROMPT_B)
  const toolUseA = a.find((x) => x.heading === 'Tool use')
  const toolUseB = changed.find((x) => x.heading === 'Tool use')
  assert.equal(toolUseA.hash, toolUseB.hash, 'untouched section keeps its hash')
})

test('sections copes with an empty or heading-free prompt', () => {
  assert.deepEqual(sections(''), [])
  assert.deepEqual(sections(null), [])
  const plain = sections('just one paragraph with no heading at all')
  assert.equal(plain.length, 1)
  assert.equal(plain[0].heading, '(preamble)')
})

test('policySentences pulls the imperative lines out of a delivered prompt', () => {
  const found = policySentences(PROMPT_B)
  assert.ok(found.includes('Do not call the AgentTool unless the user requested it.'))
  assert.ok(found.includes("Never read another worker's draft output."))
  assert.equal(policySentences(PROMPT_A).length, 0)
  assert.deepEqual(policySentences(''), [])
  assert.deepEqual(policySentences(null), [])
})

test('toolGateSentences finds every mention of a delegation tool', () => {
  assert.deepEqual(toolGateSentences(PROMPT_A), [
    'You may call tools to accomplish the task.',
    'Use the AgentTool to fan out when the task list has independent items.',
  ])
  assert.deepEqual(toolGateSentences('nothing relevant in this sentence at all'), [])
  assert.deepEqual(toolGateSentences('Do not spawn a subagent for a one-line edit.', ['subagent']), [
    'Do not spawn a subagent for a one-line edit.',
  ])
})

test('diffPrompts reports the section that changed and the constraint that landed', () => {
  const d = diffPrompts(PROMPT_A, PROMPT_B)
  assert.deepEqual(d.added.map((s) => s.heading), ['Safety'])
  assert.deepEqual(d.removed, [])
  assert.deepEqual(d.changed.map((c) => c.heading), ['Delegation'])
  assert.ok(d.policyAdded.includes('Do not call the AgentTool unless the user requested it.'))
  assert.ok(d.policyAdded.includes("Never read another worker's draft output."))
  assert.deepEqual(d.policyRemoved, [])
  assert.equal(d.charsBefore, PROMPT_A.length)
  assert.equal(d.charsAfter, PROMPT_B.length)
})

test('diffPrompts is empty for an unchanged prompt and survives empties', () => {
  const same = diffPrompts(PROMPT_A, PROMPT_A)
  assert.deepEqual(same.added, [])
  assert.deepEqual(same.removed, [])
  assert.deepEqual(same.changed, [])
  assert.deepEqual(same.policyAdded, [])
  const empty = diffPrompts(null, undefined)
  assert.deepEqual(empty.policyAdded, [])
  assert.equal(empty.charsBefore, 0)
})

test('diffPrompts reports a removed section, not just an added one', () => {
  const d = diffPrompts(PROMPT_B, PROMPT_A)
  assert.deepEqual(d.removed.map((s) => s.heading), ['Safety'])
  assert.deepEqual(d.added, [])
  assert.ok(d.policyRemoved.includes('Do not call the AgentTool unless the user requested it.'))
  assert.deepEqual(d.policyAdded, [])
})

/* ------------------------------------------------------------------ *
 * selfreport.js — grading a first-person report of the delegation gate
 * ------------------------------------------------------------------ */

test('classifySentence needs BOTH a mechanism and a restriction to call it a gate', () => {
  const gate = classifySentence('Do not call the AgentTool unless the user requested it.')
  assert.equal(gate.isGate, true)
  assert.ok(gate.mechanisms.includes('agent-tool'))
  assert.ok(gate.restrictions.includes('user-gated'))

  // Names the mechanism, restricts nothing — that is documentation.
  const mention = classifySentence('Use the AgentTool to fan out across independent files.')
  assert.equal(mention.isGate, false)
  assert.ok(mention.mechanisms.includes('agent-tool'))
  assert.deepEqual(mention.restrictions, [])

  // Restricts something, names no delegation mechanism — unrelated policy.
  assert.equal(classifySentence('Never delete a file you did not create.'), null)
  assert.equal(classifySentence(''), null)
  assert.equal(classifySentence(null), null)
})

test('classifySentence scores a user-conditional gate above a bare prohibition', () => {
  const strong = classifySentence('Do not call the AgentTool unless the user requested it.')
  const weaker = classifySentence('Avoid using subagents here.')
  assert.ok(strong.score > weaker.score, `${strong.score} should exceed ${weaker.score}`)
})

test('parseSelfReport reads the GATE: line format and tolerates preamble', () => {
  const parsed = parseSelfReport(`
    Here is what I found in my instructions:
    GATE: Do not call the AgentTool unless the user requested it.
    GATE: "Use subagents in parallel for independent work."
    Hope that helps!
  `)
  assert.equal(parsed.declaredNone, false)
  assert.equal(parsed.sentences.length, 2)
  assert.equal(parsed.gates.length, 1)
  assert.equal(parsed.mentions.length, 1)
  // Surrounding quotes are stripped so the same sentence diffs equal next time.
  assert.equal(parsed.sentences[1], 'Use subagents in parallel for independent work.')
})

test('parseSelfReport recognises an explicit NONE', () => {
  const parsed = parseSelfReport('NONE')
  assert.equal(parsed.declaredNone, true)
  assert.deepEqual(parsed.gates, [])
  // A NONE alongside a GATE line is not a NONE.
  assert.equal(parseSelfReport('NONE\nGATE: Never use the AgentTool.').declaredNone, false)
  assert.equal(parseSelfReport('').declaredNone, false)
})

test('confidence never reports a self-report as ground truth', () => {
  const strong = confidence(parseSelfReport('GATE: Do not call the AgentTool unless the user requested it.'))
  assert.equal(strong.level, 'strong')

  const none = confidence(parseSelfReport('NONE'))
  assert.equal(none.level, 'reported-absent')
  assert.match(none.note, /confirm behaviourally/i)

  const inconclusive = confidence(parseSelfReport('GATE: Use the AgentTool to fan out.'))
  assert.equal(inconclusive.level, 'inconclusive')
  assert.equal(inconclusive.score, 0)
})

test('buildRecord is deterministic when the timestamp is supplied', () => {
  const args = {
    text: 'GATE: Do not call the AgentTool unless the user requested it.',
    model: 'claude-opus-5',
    capturedAt: '2026-08-17T00:00:00.000Z',
  }
  const a = buildRecord(args)
  const b = buildRecord(args)
  assert.deepEqual(a, b)
  assert.equal(a.hash.length, 16)
  assert.equal(a.kind, 'self-report')
  assert.equal(a.gates.length, 1)
  // The stored record must carry its own caveat, so the file cannot be
  // mistaken for a byte capture later.
  assert.match(a.caveat, /not captured off the wire/i)
})

test('diffSelfReports shows a gate appearing between two reports', () => {
  const before = buildRecord({ text: 'NONE', capturedAt: '2026-08-16T00:00:00.000Z' })
  const after = buildRecord({
    text: 'GATE: Do not call the AgentTool unless the user requested it.',
    capturedAt: '2026-08-17T00:00:00.000Z',
  })
  const d = diffSelfReports(before, after)
  assert.deepEqual(d.added, ['Do not call the AgentTool unless the user requested it.'])
  assert.deepEqual(d.removed, [])
  assert.deepEqual(d.unchanged, [])

  const same = diffSelfReports(after, after)
  assert.deepEqual(same.added, [])
  assert.equal(same.unchanged.length, 1)
})

/* ------------------------------------------------------------------ *
 * module load guard
 *
 * The heuristic tests above import extract/probe/selfreport only, so a
 * syntax error in a CLI wrapper passed the whole suite green — an unescaped
 * backtick in probe-cmd.js once closed its help template early and `argo
 * drift probe` died at import with no test noticing. Load every module in
 * the directory and assert the command contract, so that cannot recur.
 * ------------------------------------------------------------------ */

test('every module under src/drift loads', async () => {
  const { readdirSync } = await import('node:fs')
  const files = readdirSync(new URL('../src/drift/', import.meta.url))
    .filter((f) => f.endsWith('.js'))
  assert.ok(files.length >= 7, `expected the full module set, saw ${files.length}`)
  for (const f of files) {
    const mod = await import(new URL(`../src/drift/${f}`, import.meta.url))
    assert.equal(typeof mod, 'object', `${f} did not evaluate to a module`)
  }
})

test('cmd.js exports run(args), and --help exits 0', async () => {
  const { run } = await import('../src/drift/cmd.js')
  assert.equal(typeof run, 'function')
  const code = await run({ help: true, _: [] })
  assert.equal(code, 0)
})

test('each drift subcommand handler takes (args, dir) and handles --help', async () => {
  const handlers = [
    ['probe-cmd.js', 'cmdProbe'],
    ['selfreport-cmd.js', 'cmdSelfReport'],
  ]
  for (const [file, name] of handlers) {
    const mod = await import(new URL(`../src/drift/${file}`, import.meta.url))
    const fn = mod[name]
    assert.equal(typeof fn, 'function', `${file} does not export ${name}`)
    assert.equal(fn.length, 2, `${name} should take (args, dir)`)
    // --help must never touch the store or the network, so a nonexistent
    // dir is a safe argument here and proves it short-circuits.
    const code = await fn({ help: true, _: [] }, '/nonexistent-drift-dir')
    assert.equal(code, 0, `${name} --help should exit 0`)
  }
})

test('drift dispatches unknown subcommands to exit 2, not a crash', async () => {
  const { run } = await import('../src/drift/cmd.js')
  assert.equal(await run({ _: ['no-such-subcommand'] }), 2)
})

/* ------------------------------------------------------------------ *
 * BOM tolerance in the self-report store
 *
 * The store is plain files a user can open. Windows editors write a UTF-8
 * BOM, which JSON.parse rejects — snapshot.js handled that but the
 * self-report reader did not, so `selfreport --list` died with a parse
 * stack trace on a record the tool had itself written.
 * ------------------------------------------------------------------ */

test('selfreport reads records that carry a UTF-8 BOM', async () => {
  const { mkdtempSync, mkdirSync, writeFileSync } = await import('node:fs')
  const { tmpdir } = await import('node:os')
  const { join } = await import('node:path')
  const { cmdSelfReport } = await import('../src/drift/selfreport-cmd.js')

  const root = mkdtempSync(join(tmpdir(), 'argo-drift-bom-'))
  const store = join(root, '.argo', 'drift', 'selfreports')
  mkdirSync(store, { recursive: true })

  const record = buildRecord({
    text: 'GATE: Do not call the AgentTool unless the user requested it.',
    capturedAt: '2026-08-17T00:00:00.000Z',
  })
  writeFileSync(join(store, 'a.json'), '\uFEFF' + JSON.stringify(record))

  const log = console.log
  const lines = []
  console.log = (...a) => lines.push(a.join(' '))
  try {
    assert.equal(await cmdSelfReport({ list: true, _: [] }, root), 0)
  } finally {
    console.log = log
  }
  assert.ok(lines.some((l) => l.includes('gates')), 'the BOM record should list')
})

test('a corrupt self-report exits 2 and names the file, not a parse trace', async () => {
  const { mkdtempSync, mkdirSync, writeFileSync } = await import('node:fs')
  const { tmpdir } = await import('node:os')
  const { join } = await import('node:path')
  const { cmdSelfReport } = await import('../src/drift/selfreport-cmd.js')

  const root = mkdtempSync(join(tmpdir(), 'argo-drift-bad-'))
  const store = join(root, '.argo', 'drift', 'selfreports')
  mkdirSync(store, { recursive: true })
  writeFileSync(join(store, 'a.json'), '{"kind":"self-report",')

  const err = console.error
  const log = console.log
  const msgs = []
  console.error = (...a) => msgs.push(a.join(' '))
  console.log = () => {}
  try {
    assert.equal(await cmdSelfReport({ list: true, _: [] }, root), 2)
  } finally {
    console.error = err
    console.log = log
  }
  assert.ok(msgs.some((m) => m.includes('a.json')), 'the message should name the file')
})
