#!/usr/bin/env node
// generate.mjs — the identity artwork, from the committed direction in directions.md.
//
//   node generate.mjs            (from this directory; needs the network once for Archivo)
//
// Writes wordmark.svg (HARBOR outlined from Archivo wdth 75 wght 600 with tools/outline-text),
// both lockups and their reversed forms, the high-water mark, icon.html, brand-sheet.html with
// every SVG inlined, and rewrites the tee mark in the apparel example with the same outlines.
// mark.svg and favicon.svg are drawn by hand and read, not written. Edit directions.md and the
// values below, then regenerate — never the generated files.

import { readFileSync, writeFileSync } from 'node:fs'
import { join, dirname } from 'node:path'
import { fileURLToPath } from 'node:url'
import { findFontkit, fetchGoogleFont, outline } from '../../../../tools/outline-text.mjs'

const DIR = dirname(fileURLToPath(import.meta.url))
const TEE = join(DIR, '..', '..', '..', 'apparel-design', 'examples', 'harbor-swim-club', 'front-mark.svg')
const NAVY = '#1f2a44', CREAM = '#efe9dc', ORANGE = '#ff5a1f'
const r2 = (n) => Number(n.toFixed(2))
const read = (f) => readFileSync(join(DIR, f), 'utf8')
const write = (f, text) => writeFileSync(join(DIR, f), text, 'utf8')

const fk = findFontkit()
if (!fk) { console.error('generate: fontkit not found — cgc install --only=deps'); process.exit(2) }
const file = await fetchGoogleFont('Archivo:wdth,wght@75,600')
const font = fk.module.create(readFileSync(file))
const V = { wdth: 75, wght: 600 }
const harbor = outline(font, 'HARBOR', { size: 71, tracking: 0.14, variation: V })
console.log(`HARBOR ${r2(harbor.width)} × cap ${r2(harbor.capHeight)} px`)

const NOTE = 'HARBOR in Archivo wdth 75 wght 600, tracked 0.14 em, outlined with cgc outline: one path, no font needed. Generated by generate.mjs from directions.md; regenerate rather than editing.'

// wordmark.svg — the cap box only
const top = harbor.baseline - harbor.capHeight
write('wordmark.svg', `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 ${r2(top)} ${r2(harbor.width)} ${r2(harbor.capHeight)}">
  <!-- ${NOTE} -->
  <path d="${harbor.d}" fill="${NAVY}"/>
</svg>
`)

// the stacked lockup on the tee's 350 grid: ring r104 stroke 16 at (175,140), bar 2 above centre, HARBOR beneath
const sx = r2(175 - harbor.width / 2), sy = r2(318 - harbor.baseline)
const stacked = (fill, bg) => `<svg xmlns="http://www.w3.org/2000/svg" width="3.5in" height="3.5in" viewBox="0 0 350 350">
  <!-- Stacked lockup, 3.5 in. ${NOTE} -->
${bg ? `  <rect width="350" height="350" fill="${bg}"/>\n` : ''}  <circle cx="175" cy="140" r="104" fill="none" stroke="${fill}" stroke-width="16"/>
  <rect x="71" y="134" width="208" height="8" fill="${fill}"/>
  <path transform="translate(${sx} ${sy})" d="${harbor.d}" fill="${fill}"/>
</svg>
`
write('lockup-stacked.svg', stacked(NAVY, null))
write('lockup-stacked-reversed.svg', stacked(CREAM, NAVY))

// the horizontal lockup: the mark at 0.4 of its grid, redrawn heavier (stroke 9) so ring and letters are one weight;
// the wordmark on the centre line; the viewBox carries the clear space (twice the mark's stroke)
const hx = 156, hy = r2(70 + harbor.capHeight / 2 - harbor.baseline)
const HW = r2(156 + harbor.width), HH = 140, CS = 13
const horizontal = (fill, bg) => `<svg xmlns="http://www.w3.org/2000/svg" viewBox="${-CS} ${-CS} ${r2(HW + 2 * CS)} ${HH + 2 * CS}">
  <!-- Horizontal lockup; the viewBox includes the clear space (twice the ring's stroke). ${NOTE} -->
${bg ? `  <rect x="${-CS}" y="${-CS}" width="${r2(HW + 2 * CS)}" height="${HH + 2 * CS}" fill="${bg}"/>\n` : ''}  <circle cx="70" cy="70" r="48" fill="none" stroke="${fill}" stroke-width="9"/>
  <rect x="18.8" y="66.9" width="102.4" height="4.5" fill="${fill}"/>
  <path transform="translate(${hx} ${hy})" d="${harbor.d}" fill="${fill}"/>
</svg>
`
write('lockup-horizontal.svg', horizontal(NAVY, null))
write('lockup-horizontal-reversed.svg', horizontal(CREAM, NAVY))

// the one variable: high water — the bar at three quarters
write('mark-high-water.svg', `<svg xmlns="http://www.w3.org/2000/svg" width="1in" height="1in" viewBox="0 0 350 350">
  <!-- The system's one variable: the waterline at three quarters, for materials about a swim at high water. Otherwise mark.svg. -->
  <circle cx="175" cy="175" r="120" fill="none" stroke="${NAVY}" stroke-width="16"/>
  <rect x="71" y="111" width="208" height="8" fill="${NAVY}"/>
</svg>
`)

// the icon master: 1024 square, no rounded corners (the platform masks), the favicon geometry
write('icon.html', `<!doctype html><html><head><meta charset="utf-8"><title>Harbor Swim Club — icon master</title>
<!-- Render: cgc render icon.html --preset app-icon  → icon-app-icon.png, the 1024 master. Keep the mark within the central 80%: platforms mask the outer ring. -->
<style>html,body{margin:0;background:${NAVY}}svg{display:block;width:1024px;height:1024px}</style></head>
<body><svg viewBox="0 0 32 32" xmlns="http://www.w3.org/2000/svg"><rect width="32" height="32" fill="${NAVY}"/><circle cx="16" cy="16" r="9" fill="none" stroke="${CREAM}" stroke-width="6"/><rect x="4" y="14.6" width="24" height="2.8" fill="${CREAM}"/></svg></body></html>
`)

// the tee mark: the same outlines, whether it still holds live text or an earlier outline
const tee = readFileSync(TEE, 'utf8')
const path = `<path transform="translate(${sx} ${sy})" d="${harbor.d}" fill="#efe9dc"/>`
const LIVE = /<text[^>]*>HARBOR<\/text>/, EARLIER = /<path transform="translate\([^)]*\)" d="[^"]*" fill="#efe9dc"\/>/
// Test for the element, do not compare strings: a regeneration that changes nothing is the
// normal case, and an unchanged file must not read as "nothing to replace".
if (!LIVE.test(tee) && !EARLIER.test(tee)) throw new Error('tee mark: found neither live text nor an earlier outline to replace')
let outlined = tee.replace(LIVE.test(tee) ? LIVE : EARLIER, path)
if (!/HARBOR is outlined/.test(outlined)) outlined = outlined.replace('Fill is the ink; the garment is the ground.', 'Fill is the ink; the garment is the ground. HARBOR is outlined (Archivo wdth 75 wght 600, tracked 0.14 em, cgc outline), so the file depends on no font.')
writeFileSync(TEE, outlined)

// the brand sheet, every SVG inlined — strip the physical size from the ROOT only
const inline = (svg) => svg.replace(/<!--[\s\S]*?-->\s*/g, '').replace(/<svg([^>]*?) width="[^"]*" height="[^"]*"/, '<svg$1').replace(/<svg /, '<svg class="art" ').trim()
const art = (f, extra = '') => inline(read(f)).replace('class="art"', `class="art"${extra ? ` style="${extra}"` : ''}`)
write('brand-sheet.html', `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1">
<title>Harbor Swim Club — identity</title>
<!--
  The brand sheet: every version of the mark, the lockups, the one variable, clear space and
  minimum sizes, colour, type, and what not to do — with every SVG inlined so the sheet is one
  file. Generated from directions.md by generate.mjs; the SVG masters sit beside it.
  Render: cgc render brand-sheet.html --full   ·   Gate: cgc audit brand-sheet.html --mobile
-->
<link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Archivo:wdth,wght@75,500;75,600;100,400;100,500&family=JetBrains+Mono:wght@400;500&display=swap" rel="stylesheet">
<style>
  :root { --cream: ${CREAM}; --navy: ${NAVY}; --orange: ${ORANGE}; --line: rgb(31 42 68 / 0.25); }
  * { box-sizing: border-box; }
  html { background: var(--cream); color: var(--navy); }
  body { margin: 0; font-family: Archivo, "Helvetica Neue", Arial, sans-serif; font-optical-sizing: auto; line-height: 1.5; font-size: 17px; }
  .page { max-width: 1320px; margin: 0 auto; padding: 40px 56px 72px; }
  .head { display: flex; justify-content: space-between; gap: 1rem; flex-wrap: wrap; font: 500 12px/1 "JetBrains Mono", ui-monospace, monospace; letter-spacing: 0.14em; text-transform: uppercase; border-bottom: 0.5px solid var(--navy); padding-bottom: 12px; }
  h1 { font: 600 clamp(2.4rem, 5vw, 4.2rem)/1 Archivo, sans-serif; font-stretch: 75%; letter-spacing: 0.04em; text-transform: uppercase; margin: 56px 0 8px; text-wrap: balance; }
  .art { max-width: 100%; height: auto; }
  .lede { max-width: 62ch; font-size: 19px; margin: 0 0 8px; text-wrap: pretty; }
  h2 { font: 500 12px/1 "JetBrains Mono", ui-monospace, monospace; letter-spacing: 0.14em; text-transform: uppercase; margin: 56px 0 18px; padding-top: 14px; border-top: 0.5px solid var(--navy); }
  .row { display: grid; gap: 24px; }
  .two { grid-template-columns: 1fr 1fr; }
  .tile { border: 0.5px solid var(--line); padding: 28px; min-height: 220px; display: flex; align-items: center; justify-content: center; }
  .tile.rev { background: var(--navy); border-color: var(--navy); }
  .tile.mark svg { width: 220px; height: 220px; }
  .tile.h svg { width: 100%; max-width: 480px; }
  .tile.s svg { width: 240px; height: 240px; }
  .cap { font: 400 13px/1.5 "JetBrains Mono", ui-monospace, monospace; color: rgb(31 42 68 / 0.75); margin: 10px 0 0; max-width: 62ch; }
  .sizes { display: flex; align-items: flex-end; gap: 40px; flex-wrap: wrap; }
  .sizes figure { margin: 0; text-align: left; }
  .sizes svg { display: block; }
  .clear { position: relative; display: inline-block; padding: 0; }
  .clear .box { position: absolute; inset: 0; border: 1px dashed var(--orange); pointer-events: none; }
  .chips { display: grid; grid-template-columns: repeat(3, 1fr); gap: 24px; }
  .chip { height: 150px; padding: 18px; display: flex; flex-direction: column; justify-content: space-between; font: 400 13px/1.45 "JetBrains Mono", ui-monospace, monospace; border: 0.5px solid var(--line); }
  .chip b { display: block; font: 600 17px/1.2 Archivo, sans-serif; font-stretch: 75%; letter-spacing: 0.06em; text-transform: uppercase; }
  .chip.navy { background: var(--navy); color: var(--cream); }
  .chip.orange { background: var(--orange); color: var(--navy); }
  .type { font: 600 64px/1 Archivo, sans-serif; font-stretch: 75%; letter-spacing: 0.14em; text-transform: uppercase; margin: 0 0 12px; }
  ul { margin: 0; padding-left: 1.2em; max-width: 62ch; } li { margin: 0 0 6px; }
  .foot { margin-top: 56px; border-top: 0.5px solid var(--navy); padding-top: 12px; font: 400 12px/1.6 "JetBrains Mono", ui-monospace, monospace; display: flex; justify-content: space-between; flex-wrap: wrap; gap: 1rem; }
  @media (max-width: 800px) { .two, .chips { grid-template-columns: 1fr; } .page { padding: 24px 20px 56px; } }
</style>
</head>
<body><div class="page">
  <header class="head"><span>Harbor Swim Club</span><span>identity · version 1</span><span>2 September 2026</span></header>

  <h1>A life-ring, half under</h1>
  <p class="lede">The mark is a ring with its waterline through the centre — a tow-float sitting half under, the way one does in open water. The wordmark is harbour signage: condensed, medium weight, tracked, and it never raises its voice. Navy of deep water; cream of a rope; orange only where safety uses it.</p>

  <h2>The mark</h2>
  <div class="row two">
    <div><div class="tile mark">${art('mark.svg')}</div><p class="cap">Navy on cream. Stroke 4.6% of the width; the waterline half that, two units above centre so it reads as centred.</p></div>
    <div><div class="tile mark rev">${art('mark.svg').replaceAll(NAVY, CREAM)}</div><p class="cap">Reversed: cream on navy. One colour in either; never a third.</p></div>
  </div>

  <h2>Lockups</h2>
  <div class="row two">
    <div><div class="tile h">${art('lockup-horizontal.svg')}</div><p class="cap">Horizontal — the wordmark on the ring's centre line. For signs, headers, the membership card.</p></div>
    <div><div class="tile h rev">${art('lockup-horizontal-reversed.svg')}</div><p class="cap">Reversed.</p></div>
    <div><div class="tile s">${art('lockup-stacked.svg')}</div><p class="cap">Stacked — the garment lockup, as on the tee's left chest and the cap.</p></div>
    <div><div class="tile s rev">${art('lockup-stacked-reversed.svg')}</div><p class="cap">Reversed — cream ink on the navy blank.</p></div>
  </div>

  <h2>The one variable</h2>
  <div class="row two">
    <div><div class="tile mark">${art('mark.svg')}</div><p class="cap">Slack water — the waterline at the centre. The mark, everywhere, always.</p></div>
    <div><div class="tile mark">${art('mark-high-water.svg')}</div><p class="cap">High water — the waterline at three quarters. Only on materials about a swim at high water; never as decoration.</p></div>
  </div>

  <h2>Clear space and minimum sizes</h2>
  <div class="sizes">
    <figure><span class="clear">${art('lockup-horizontal.svg', 'width:480px')}<span class="box"></span></span><p class="cap">Clear space on every side: twice the ring's stroke (the dashed box). Nothing enters it.</p></figure>
  </div>
  <div class="sizes" style="margin-top:28px">
    <figure>${art('lockup-horizontal.svg', 'width:100px')}<p class="cap">Lockup minimum: 100 px · 1 in</p></figure>
    <figure>${art('mark.svg', 'width:64px;height:64px')}<p class="cap">Mark at 64 px — mark.svg</p></figure>
    <figure>${art('favicon.svg', 'width:48px;height:48px')}<p class="cap">48 px — favicon.svg</p></figure>
    <figure>${art('favicon.svg', 'width:32px;height:32px')}<p class="cap">32 px</p></figure>
    <figure>${art('favicon.svg', 'width:16px;height:16px')}<p class="cap">16 px — redrawn: stroke 22%, not 4.6%</p></figure>
  </div>

  <h2>Colour</h2>
  <div class="chips">
    <div class="chip navy"><b>Navy</b><span>${NAVY}<br>Pantone 2767 C (confirm)<br>the water; the ground for cream</span></div>
    <div class="chip"><b>Cream</b><span>${CREAM}<br>Pantone 7499 C<br>the rope; ink on navy, ground for navy</span></div>
    <div class="chip orange"><b>Tow-float orange</b><span>${ORANGE}<br>Pantone 1655 C (confirm)<br>one use: the flags on safety notices</span></div>
  </div>

  <h2>Type</h2>
  <p class="type">Harbor Swim Club</p>
  <p class="cap">Archivo, width 75, weight 600, caps, tracked 0.14 em — harbour signage. The wordmark is delivered as outlines (cgc outline); this line is the live face for everything else: headings tracked 0.06 em, body at width 100 weight 400.</p>

  <h2>Never</h2>
  <ul>
    <li>A gradient, a shadow, a rotation, or an outline stroke around the wordmark.</li>
    <li>The ring without its waterline; the waterline anywhere but the centre or three quarters.</li>
    <li>Orange for anything but the flags. A third colour of any kind.</li>
    <li>mark.svg scaled below 0.25 in / 16 px — use favicon.svg, which is redrawn for it.</li>
    <li>The wordmark set live in a font and sent to a shop. Send the outlines.</li>
  </ul>

  <footer class="foot"><span>Files: mark.svg · mark-high-water.svg · wordmark.svg · lockup-horizontal(-reversed).svg · lockup-stacked(-reversed).svg · favicon.svg · icon.html → icon-app-icon.png</span><span>directions.md · spec-sheet.txt · review.md · generate.mjs</span></footer>
</div></body>
</html>
`)
console.log('written: wordmark, lockups (+reversed), high-water mark, icon.html, brand-sheet.html; tee mark outlined')
