#!/usr/bin/env node
// Regenerates .claude/memory/INDEX.md from the memory files. No dependencies, node >=18.
// Copy into <project>/.claude/memory/ and run: node .claude/memory/build-index.mjs
import { readFileSync, writeFileSync, readdirSync, existsSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const DIR = dirname(fileURLToPath(import.meta.url));
const read = f => existsSync(join(DIR, f)) ? readFileSync(join(DIR, f), 'utf8') : '';

// Minimal frontmatter reader: flat scalars plus one inline [a, b] array. That is the whole
// schema this store uses; a YAML dependency for it would be absurd.
function frontmatter(src) {
  const m = /^---\r?\n([\s\S]*?)\r?\n---/.exec(src);
  if (!m) return {};
  const out = {};
  for (const line of m[1].split(/\r?\n/)) {
    const kv = /^([A-Za-z_][\w-]*):\s*(.*)$/.exec(line);
    if (!kv) continue;
    let v = kv[2].trim().replace(/\s+#.*$/, '');
    if (/^\[.*\]$/.test(v)) v = v.slice(1, -1).split(',').map(s => s.trim()).filter(Boolean);
    out[kv[1]] = v;
  }
  return out;
}

const decDir = join(DIR, 'decisions');
const decisions = (existsSync(decDir) ? readdirSync(decDir) : [])
  .filter(f => f.endsWith('.md'))
  .map(f => ({ file: `decisions/${f}`, ...frontmatter(readFileSync(join(decDir, f), 'utf8')) }))
  .filter(d => d.id)
  .sort((a, b) => String(b.id).localeCompare(String(a.id)));

// Open items are the unchecked "- [ ] `ID` text" lines; everything else is noise.
const open = src => src.split(/\r?\n/)
  .filter(l => /^\s*-\s*\[\s\]/.test(l))
  .map(l => l.replace(/^\s*-\s*\[\s\]\s*/, '').trim());

const questions = open(read('questions.md'));
const backlog = open(read('backlog.md'));
const blocked = backlog.filter(l => /\(blocked:/.test(l)).length;

// Freshness comes from the data, never from Date.now() — a generated timestamp would churn the
// git diff on every run and teach everyone to ignore it.
const stamp = [
  ...decisions.map(d => d.date),
  frontmatter(read('questions.md')).updated,
  frontmatter(read('backlog.md')).updated,
  frontmatter(read('facts.md')).updated,
].filter(Boolean).sort().pop() || 'unknown';

const live = decisions.filter(d => d.status !== 'superseded' && d.status !== 'reversed');
const row = d => `| \`${d.id}\` | ${d.date || ''} | ${d.status || ''} | [${d.title || d.file}](${d.file}) | ${d.verify ? `\`${d.verify}\`` : ''} |`;

const out = `<!-- GENERATED by build-index.mjs — do not edit. Run: node .claude/memory/build-index.mjs -->
# Project memory

Newest entry ${stamp} · ${live.length} live decision(s)${decisions.length - live.length ? ` (+${decisions.length - live.length} superseded/reversed)` : ''} · ${questions.length} open question(s) · ${backlog.length} open backlog item(s)${blocked ? `, ${blocked} blocked` : ''}

Read this file first. Open the individual files only when a line below is relevant to the work
at hand. Durable project facts: [facts.md](facts.md).

## Open questions
${questions.length ? questions.map(q => `- ${q}`).join('\n') : '_none_'}

## Backlog — open
${backlog.length ? backlog.map(b => `- ${b}`).join('\n') : '_none_'}

## Decisions
${decisions.length ? `| id | date | status | title | verify |\n|---|---|---|---|---|\n${decisions.map(row).join('\n')}` : '_none_'}
`;

writeFileSync(join(DIR, 'INDEX.md'), out);
console.log(`INDEX.md: ${decisions.length} decisions, ${questions.length} questions, ${backlog.length} backlog.`);
